// Copyright © 2023 OpenIM SDK. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//go:build js && wasm
// +build js,wasm

package main

import (
	"fmt"
	"runtime"
	"runtime/debug"
	"syscall/js"

	"github.com/openimsdk/openim-sdk-core/v3/wasm/wasm_wrapper"
)

func main() {
	defer func() {
		if r := recover(); r != nil {
			fmt.Println("MAIN", "panic info is:", r, debug.Stack())
		}
	}()
	fmt.Println("runtime env", runtime.GOARCH, runtime.GOOS)
	registerFunc()
	<-make(chan bool)
}

func registerFunc() {
	//register global listener function
	globalFuc := wasm_wrapper.NewWrapperCommon()
	js.Global().Set(wasm_wrapper.COMMONEVENTFUNC, js.FuncOf(globalFuc.CommonEventFunc))
	//register init login function
	wrapperInitLogin := wasm_wrapper.NewWrapperInitLogin(globalFuc)
	js.Global().Set("initSDK", js.FuncOf(wrapperInitLogin.InitSDK))
	js.Global().Set("generateCaptcha", js.FuncOf(wrapperInitLogin.GenerateCaptcha))
	js.Global().Set("verifyCaptcha", js.FuncOf(wrapperInitLogin.VerifyCaptcha))
	js.Global().Set("login", js.FuncOf(wrapperInitLogin.Login))
	js.Global().Set("logout", js.FuncOf(wrapperInitLogin.Logout))
	js.Global().Set("getLoginStatus", js.FuncOf(wrapperInitLogin.GetLoginStatus))
	js.Global().Set("setAppBackgroundStatus", js.FuncOf(wrapperInitLogin.SetAppBackgroundStatus))
	js.Global().Set("networkStatusChanged", js.FuncOf(wrapperInitLogin.NetworkStatusChanged))

	//register conversation and message function
	wrapperConMsg := wasm_wrapper.NewWrapperConMsg(globalFuc)
	js.Global().Set("createTextMessage", js.FuncOf(wrapperConMsg.CreateTextMessage))
	js.Global().Set("createImageMessage", js.FuncOf(wrapperConMsg.CreateImageMessage))
	js.Global().Set("createImageMessageByURL", js.FuncOf(wrapperConMsg.CreateImageMessageByURL))
	js.Global().Set("createSoundMessageByURL", js.FuncOf(wrapperConMsg.CreateSoundMessageByURL))
	js.Global().Set("createVideoMessageByURL", js.FuncOf(wrapperConMsg.CreateVideoMessageByURL))
	js.Global().Set("createFileMessageByURL", js.FuncOf(wrapperConMsg.CreateFileMessageByURL))
	js.Global().Set("createCustomMessage", js.FuncOf(wrapperConMsg.CreateCustomMessage))
	js.Global().Set("createQuoteMessage", js.FuncOf(wrapperConMsg.CreateQuoteMessage))
	js.Global().Set("createAdvancedQuoteMessage", js.FuncOf(wrapperConMsg.CreateAdvancedQuoteMessage))
	js.Global().Set("createAdvancedTextMessage", js.FuncOf(wrapperConMsg.CreateAdvancedTextMessage))
	js.Global().Set("createCardMessage", js.FuncOf(wrapperConMsg.CreateCardMessage))
	js.Global().Set("createTextAtMessage", js.FuncOf(wrapperConMsg.CreateTextAtMessage))
	js.Global().Set("createVideoMessage", js.FuncOf(wrapperConMsg.CreateVideoMessage))
	js.Global().Set("createFileMessage", js.FuncOf(wrapperConMsg.CreateFileMessage))
	js.Global().Set("createMergerMessage", js.FuncOf(wrapperConMsg.CreateMergerMessage))
	js.Global().Set("createFaceMessage", js.FuncOf(wrapperConMsg.CreateFaceMessage))
	js.Global().Set("createForwardMessage", js.FuncOf(wrapperConMsg.CreateForwardMessage))
	js.Global().Set("createLocationMessage", js.FuncOf(wrapperConMsg.CreateLocationMessage))
	js.Global().Set("createVideoMessageFromFullPath", js.FuncOf(wrapperConMsg.CreateVideoMessageFromFullPath))
	js.Global().Set("createImageMessageFromFullPath", js.FuncOf(wrapperConMsg.CreateImageMessageFromFullPath))

	js.Global().Set("createSoundMessageFromFullPath", js.FuncOf(wrapperConMsg.CreateSoundMessageFromFullPath))
	js.Global().Set("createFileMessageFromFullPath", js.FuncOf(wrapperConMsg.CreateFileMessageFromFullPath))
	js.Global().Set("createSoundMessage", js.FuncOf(wrapperConMsg.CreateSoundMessage))
	js.Global().Set("createForwardMessage", js.FuncOf(wrapperConMsg.CreateForwardMessage))
	js.Global().Set("createLocationMessage", js.FuncOf(wrapperConMsg.CreateLocationMessage))
	js.Global().Set("createVideoMessageFromFullPath", js.FuncOf(wrapperConMsg.CreateVideoMessageFromFullPath))
	js.Global().Set("createImageMessageFromFullPath", js.FuncOf(wrapperConMsg.CreateImageMessageFromFullPath))
	js.Global().Set("getAtAllTag", js.FuncOf(wrapperConMsg.GetAtAllTag))
	js.Global().Set("markConversationMessageAsRead", js.FuncOf(wrapperConMsg.MarkConversationMessageAsRead))
	js.Global().Set("markAllConversationMessageAsRead", js.FuncOf(wrapperConMsg.MarkAllConversationMessageAsRead))
	js.Global().Set("markMessagesAsReadByMsgID", js.FuncOf(wrapperConMsg.MarkMessagesAsReadByMsgID))
	js.Global().Set("markGroupMsgsAsRead", js.FuncOf(wrapperConMsg.MarkGroupMsgsAsRead))
	js.Global().Set("sendMessage", js.FuncOf(wrapperConMsg.SendMessage))
	js.Global().Set("sendMessageNotOss", js.FuncOf(wrapperConMsg.SendMessageNotOss))
	js.Global().Set("getAllConversationList", js.FuncOf(wrapperConMsg.GetAllConversationList))
	js.Global().Set("getConversationListSplit", js.FuncOf(wrapperConMsg.GetConversationListSplit))
	js.Global().Set("getOneConversation", js.FuncOf(wrapperConMsg.GetOneConversation))
	js.Global().Set("deleteConversationAndDeleteAllMsg", js.FuncOf(wrapperConMsg.DeleteConversationAndDeleteAllMsg))
	js.Global().Set("getAdvancedHistoryMessageList", js.FuncOf(wrapperConMsg.GetAdvancedHistoryMessageList))
	js.Global().Set("getAdvancedHistoryMessageListReverse", js.FuncOf(wrapperConMsg.GetAdvancedHistoryMessageListReverse))
	js.Global().Set("getMultipleConversation", js.FuncOf(wrapperConMsg.GetMultipleConversation))
	js.Global().Set("hideConversation", js.FuncOf(wrapperConMsg.HideConversation))
	js.Global().Set("setConversationDraft", js.FuncOf(wrapperConMsg.SetConversationDraft))
	js.Global().Set("setConversation", js.FuncOf(wrapperConMsg.SetConversation))
	js.Global().Set("setConversationMute", js.FuncOf(wrapperConMsg.SetConversationMute))

	js.Global().Set("getTotalUnreadMsgCount", js.FuncOf(wrapperConMsg.GetTotalUnreadMsgCount))
	js.Global().Set("findMessageList", js.FuncOf(wrapperConMsg.FindMessageList))

	js.Global().Set("revokeMessage", js.FuncOf(wrapperConMsg.RevokeMessage))
	js.Global().Set("reportSpam", js.FuncOf(wrapperConMsg.ReportSpam))
	js.Global().Set("sendPaymentNotification", js.FuncOf(wrapperConMsg.SendPaymentNotification))
	js.Global().Set("notifyRedPacketClaimed", js.FuncOf(wrapperConMsg.NotifyRedPacketClaimed))
	js.Global().Set("notifyTransferReceived", js.FuncOf(wrapperConMsg.NotifyTransferReceived))
	js.Global().Set("notifyRedPacketExpired", js.FuncOf(wrapperConMsg.NotifyRedPacketExpired))
	js.Global().Set("notifyTransferExpired", js.FuncOf(wrapperConMsg.NotifyTransferExpired))
	js.Global().Set("getLinkPreview", js.FuncOf(wrapperConMsg.GetLinkPreview))
	js.Global().Set("typingStatusUpdate", js.FuncOf(wrapperConMsg.TypingStatusUpdate))
	js.Global().Set("deleteMessageFromLocalStorage", js.FuncOf(wrapperConMsg.DeleteMessageFromLocalStorage))
	js.Global().Set("deleteMessage", js.FuncOf(wrapperConMsg.DeleteMessage))
	js.Global().Set("deleteMessageWithOptions", js.FuncOf(wrapperConMsg.DeleteMessageWithOptions))
	js.Global().Set("hideAllConversations", js.FuncOf(wrapperConMsg.HideAllConversations))
	js.Global().Set("deleteAllMsgFromLocalAndSvr", js.FuncOf(wrapperConMsg.DeleteAllMsgFromLocalAndSvr))
	js.Global().Set("deleteAllMsgFromLocal", js.FuncOf(wrapperConMsg.DeleteAllMsgFromLocal))
	js.Global().Set("clearConversationAndDeleteAllMsg", js.FuncOf(wrapperConMsg.ClearConversationAndDeleteAllMsg))
	js.Global().Set("insertSingleMessageToLocalStorage", js.FuncOf(wrapperConMsg.InsertSingleMessageToLocalStorage))
	js.Global().Set("insertGroupMessageToLocalStorage", js.FuncOf(wrapperConMsg.InsertGroupMessageToLocalStorage))
	js.Global().Set("searchLocalMessages", js.FuncOf(wrapperConMsg.SearchLocalMessages))
	js.Global().Set("setMessageLocalEx", js.FuncOf(wrapperConMsg.SetMessageLocalEx))
	js.Global().Set("searchConversation", js.FuncOf(wrapperConMsg.SearchConversation))

	js.Global().Set("changeInputStates", js.FuncOf(wrapperConMsg.ChangeInputStates))
	js.Global().Set("getInputStates", js.FuncOf(wrapperConMsg.GetInputStates))

	//register group func
	wrapperGroup := wasm_wrapper.NewWrapperGroup(globalFuc)
	js.Global().Set("createGroup", js.FuncOf(wrapperGroup.CreateGroup))
	js.Global().Set("getSpecifiedGroupsInfo", js.FuncOf(wrapperGroup.GetSpecifiedGroupsInfo))
	js.Global().Set("joinGroup", js.FuncOf(wrapperGroup.JoinGroup))
	js.Global().Set("quitGroup", js.FuncOf(wrapperGroup.QuitGroup))
	js.Global().Set("dismissGroup", js.FuncOf(wrapperGroup.DismissGroup))
	js.Global().Set("changeGroupMute", js.FuncOf(wrapperGroup.ChangeGroupMute))
	js.Global().Set("changeGroupMemberMute", js.FuncOf(wrapperGroup.ChangeGroupMemberMute))
	js.Global().Set("setGroupMemberInfo", js.FuncOf(wrapperGroup.SetGroupMemberInfo))
	js.Global().Set("getJoinedGroupList", js.FuncOf(wrapperGroup.GetJoinedGroupList))
	js.Global().Set("getJoinedGroupListPage", js.FuncOf(wrapperGroup.GetJoinedGroupListPage))
	js.Global().Set("searchGroups", js.FuncOf(wrapperGroup.SearchGroups))
	js.Global().Set("setGroupInfo", js.FuncOf(wrapperGroup.SetGroupInfo))
	js.Global().Set("setSendMessageSetting", js.FuncOf(wrapperGroup.SetSendMessageSetting))
	js.Global().Set("getGroupSetting", js.FuncOf(wrapperGroup.GetGroupSetting))
	js.Global().Set("getSendMessageSetting", js.FuncOf(wrapperGroup.GetSendMessageSetting))
	js.Global().Set("setInviteSetting", js.FuncOf(wrapperGroup.SetInviteSetting))
	js.Global().Set("getInviteSetting", js.FuncOf(wrapperGroup.GetInviteSetting))
	js.Global().Set("setPinSetting", js.FuncOf(wrapperGroup.SetPinSetting))
	js.Global().Set("getPinSetting", js.FuncOf(wrapperGroup.GetPinSetting))
	js.Global().Set("setEditSetting", js.FuncOf(wrapperGroup.SetEditSetting))
	js.Global().Set("getEditSetting", js.FuncOf(wrapperGroup.GetEditSetting))
	js.Global().Set("setBurnSetting", js.FuncOf(wrapperGroup.SetBurnSetting))
	js.Global().Set("getBurnSetting", js.FuncOf(wrapperGroup.GetBurnSetting))
	js.Global().Set("setMsgBurnDuration", js.FuncOf(wrapperGroup.SetMsgBurnDuration))
	js.Global().Set("getMsgBurnDuration", js.FuncOf(wrapperGroup.GetMsgBurnDuration))
	js.Global().Set("setGroupAnnouncement", js.FuncOf(wrapperGroup.SetGroupAnnouncement))
	js.Global().Set("getGroupAnnouncement", js.FuncOf(wrapperGroup.GetGroupAnnouncement))
	js.Global().Set("setInviteLinkSetting", js.FuncOf(wrapperGroup.SetInviteLinkSetting))
	js.Global().Set("createGroupInviteLink", js.FuncOf(wrapperGroup.CreateGroupInviteLink))
	js.Global().Set("getGroupInviteLink", js.FuncOf(wrapperGroup.GetGroupInviteLink))
	js.Global().Set("joinGroupByInviteLink", js.FuncOf(wrapperGroup.JoinGroupByInviteLink))
	js.Global().Set("revokeGroupInviteLink", js.FuncOf(wrapperGroup.RevokeGroupInviteLink))
	js.Global().Set("listGroupInviteLinks", js.FuncOf(wrapperGroup.ListGroupInviteLinks))
	js.Global().Set("getGroupMemberList", js.FuncOf(wrapperGroup.GetGroupMemberList))
	js.Global().Set("getGroupMemberOwnerAndAdmin", js.FuncOf(wrapperGroup.GetGroupMemberOwnerAndAdmin))
	js.Global().Set("getGroupMemberListByJoinTimeFilter", js.FuncOf(wrapperGroup.GetGroupMemberListByJoinTimeFilter))
	js.Global().Set("getSpecifiedGroupMembersInfo", js.FuncOf(wrapperGroup.GetSpecifiedGroupMembersInfo))
	js.Global().Set("kickGroupMember", js.FuncOf(wrapperGroup.KickGroupMember))
	js.Global().Set("transferGroupOwner", js.FuncOf(wrapperGroup.TransferGroupOwner))
	js.Global().Set("inviteUserToGroup", js.FuncOf(wrapperGroup.InviteUserToGroup))
	js.Global().Set("getGroupApplicationListAsRecipient", js.FuncOf(wrapperGroup.GetGroupApplicationListAsRecipient))
	js.Global().Set("getGroupApplicationListAsApplicant", js.FuncOf(wrapperGroup.GetGroupApplicationListAsApplicant))
	js.Global().Set("acceptGroupApplication", js.FuncOf(wrapperGroup.AcceptGroupApplication))
	js.Global().Set("refuseGroupApplication", js.FuncOf(wrapperGroup.RefuseGroupApplication))
	js.Global().Set("searchGroupMembers", js.FuncOf(wrapperGroup.SearchGroupMembers))
	js.Global().Set("isJoinGroup", js.FuncOf(wrapperGroup.IsJoinGroup))
	js.Global().Set("getUsersInGroup", js.FuncOf(wrapperGroup.GetUsersInGroup))
	js.Global().Set("getGroupApplicationUnhandledCount", js.FuncOf(wrapperGroup.GetGroupApplicationUnhandledCount))
	js.Global().Set("getCommonGroupsWithFriend", js.FuncOf(wrapperGroup.GetCommonGroupsWithFriend))
	js.Global().Set("pinGroupMessage", js.FuncOf(wrapperGroup.PinGroupMessage))
	js.Global().Set("unpinGroupMessage", js.FuncOf(wrapperGroup.UnpinGroupMessage))
	js.Global().Set("getGroupPinnedMessages", js.FuncOf(wrapperGroup.GetGroupPinnedMessages))
	js.Global().Set("setGroupMute", js.FuncOf(wrapperGroup.SetGroupMute))
	js.Global().Set("getGroupMute", js.FuncOf(wrapperGroup.GetGroupMute))
	js.Global().Set("pinGroup", js.FuncOf(wrapperGroup.PinGroup))
	js.Global().Set("unpinGroup", js.FuncOf(wrapperGroup.UnpinGroup))

	wrapperUser := wasm_wrapper.NewWrapperUser(globalFuc)
	js.Global().Set("getSelfUserInfo", js.FuncOf(wrapperUser.GetSelfUserInfo))
	js.Global().Set("setSelfInfo", js.FuncOf(wrapperUser.SetSelfInfo))
	js.Global().Set("getUsersInfo", js.FuncOf(wrapperUser.GetUsersInfo))
	js.Global().Set("subscribeUsersStatus", js.FuncOf(wrapperUser.SubscribeUsersStatus))
	js.Global().Set("unsubscribeUsersStatus", js.FuncOf(wrapperUser.UnsubscribeUsersStatus))
	js.Global().Set("getSubscribeUsersStatus", js.FuncOf(wrapperUser.GetSubscribeUsersStatus))
	js.Global().Set("getUserStatus", js.FuncOf(wrapperUser.GetUserStatus))
	js.Global().Set("phoneGetSNInfo", js.FuncOf(wrapperUser.PhoneGetSNInfo))
	js.Global().Set("phoneSetSNInfo", js.FuncOf(wrapperUser.PhoneSetSNInfo))
	js.Global().Set("setPhoneVisibility", js.FuncOf(wrapperUser.SetPhoneVisibility))
	js.Global().Set("setCallAcceptSetting", js.FuncOf(wrapperUser.SetCallAcceptSetting))
	js.Global().Set("setMsgReceiveSetting", js.FuncOf(wrapperUser.SetMsgReceiveSetting))
	js.Global().Set("setGroupInviteSetting", js.FuncOf(wrapperUser.SetGroupInviteSetting))
	js.Global().Set("setUserMsgBurnDuration", js.FuncOf(wrapperUser.SetUserMsgBurnDuration))
	js.Global().Set("setDeleteAccountInterval", js.FuncOf(wrapperUser.SetDeleteAccountInterval))
	js.Global().Set("getUserPrivacySettings", js.FuncOf(wrapperUser.GetUserPrivacySettings))
	js.Global().Set("setMsgNotificationSwitch", js.FuncOf(wrapperUser.SetMsgNotificationSwitch))
	js.Global().Set("setSokimPaymentNotificationSwitch", js.FuncOf(wrapperUser.SetSokimPaymentNotificationSwitch))
	js.Global().Set("setSokimServiceNotificationSwitch", js.FuncOf(wrapperUser.SetSokimServiceNotificationSwitch))
	js.Global().Set("setAvNotificationSwitch", js.FuncOf(wrapperUser.SetAvNotificationSwitch))
	js.Global().Set("setAvCallRingtoneSwitch", js.FuncOf(wrapperUser.SetAvCallRingtoneSwitch))
	js.Global().Set("setPlayCalleeRingtoneOnAnswerSwitch", js.FuncOf(wrapperUser.SetPlayCalleeRingtoneOnAnswerSwitch))
	js.Global().Set("getUserNotificationSettings", js.FuncOf(wrapperUser.GetUserNotificationSettings))
	js.Global().Set("getUserByPhone", js.FuncOf(wrapperUser.GetUserByPhone))
	js.Global().Set("getUsersByNickname", js.FuncOf(wrapperUser.GetUsersByNickname))
	js.Global().Set("checkNickname", js.FuncOf(wrapperUser.CheckNickname))
	js.Global().Set("checkUserExist", js.FuncOf(wrapperUser.CheckUserExist))

	wrapperFriend := wasm_wrapper.NewWrapperFriend(globalFuc)
	js.Global().Set("getSpecifiedFriendsInfo", js.FuncOf(wrapperFriend.GetSpecifiedFriendsInfo))
	js.Global().Set("getFriendList", js.FuncOf(wrapperFriend.GetFriendList))
	js.Global().Set("getFriendListPage", js.FuncOf(wrapperFriend.GetFriendListPage))
	js.Global().Set("searchFriends", js.FuncOf(wrapperFriend.SearchFriends))
	js.Global().Set("searchFriendsByProfile", js.FuncOf(wrapperFriend.SearchFriendsByProfile))
	js.Global().Set("checkFriend", js.FuncOf(wrapperFriend.CheckFriend))
	js.Global().Set("addFriend", js.FuncOf(wrapperFriend.AddFriend))
	js.Global().Set("updateFriends", js.FuncOf(wrapperFriend.UpdateFriends))
	js.Global().Set("setFriendName", js.FuncOf(wrapperFriend.SetFriendName))
	js.Global().Set("setFriendNote", js.FuncOf(wrapperFriend.SetFriendNote))
	js.Global().Set("deleteFriend", js.FuncOf(wrapperFriend.DeleteFriend))
	js.Global().Set("deleteFriendOneway", js.FuncOf(wrapperFriend.DeleteFriendOneway))
	js.Global().Set("getFriendApplicationListAsRecipient", js.FuncOf(wrapperFriend.GetFriendApplicationListAsRecipient))
	js.Global().Set("getFriendApplicationListAsApplicant", js.FuncOf(wrapperFriend.GetFriendApplicationListAsApplicant))
	js.Global().Set("acceptFriendApplication", js.FuncOf(wrapperFriend.AcceptFriendApplication))
	js.Global().Set("refuseFriendApplication", js.FuncOf(wrapperFriend.RefuseFriendApplication))
	js.Global().Set("getBlackList", js.FuncOf(wrapperFriend.GetBlackList))
	js.Global().Set("removeBlack", js.FuncOf(wrapperFriend.RemoveBlack))
	js.Global().Set("addBlack", js.FuncOf(wrapperFriend.AddBlack))
	js.Global().Set("getFriendApplicationUnhandledCount", js.FuncOf(wrapperFriend.GetFriendApplicationUnhandledCount))
	js.Global().Set("setFriendMute", js.FuncOf(wrapperFriend.SetFriendMute))
	js.Global().Set("getFriendMute", js.FuncOf(wrapperFriend.GetFriendMute))
	js.Global().Set("getFriendPhone", js.FuncOf(wrapperFriend.GetFriendPhone))
	js.Global().Set("pinFriend", js.FuncOf(wrapperFriend.PinFriend))
	js.Global().Set("unpinFriend", js.FuncOf(wrapperFriend.UnpinFriend))

	wrapperThird := wasm_wrapper.NewWrapperThird(globalFuc)
	js.Global().Set("updateFcmToken", js.FuncOf(wrapperThird.UpdateFcmToken))
	js.Global().Set("uploadFile", js.FuncOf(wrapperThird.UploadFile))

	wrapperSignaling := wasm_wrapper.NewWrapperSignaling(globalFuc)
	js.Global().Set("signalingInvite", js.FuncOf(wrapperSignaling.SignalingInvite))
	js.Global().Set("signalingInviteInGroup", js.FuncOf(wrapperSignaling.SignalingInviteInGroup))
	js.Global().Set("signalingAccept", js.FuncOf(wrapperSignaling.SignalingAccept))
	js.Global().Set("signalingJoin", js.FuncOf(wrapperSignaling.SignalingJoin))
	js.Global().Set("signalingReject", js.FuncOf(wrapperSignaling.SignalingReject))
	js.Global().Set("signalingCancel", js.FuncOf(wrapperSignaling.SignalingCancel))
	js.Global().Set("signalingTimeout", js.FuncOf(wrapperSignaling.SignalingTimeout))
	js.Global().Set("signalingHungUp", js.FuncOf(wrapperSignaling.SignalingHungUp))
	js.Global().Set("signalingHeartbeat", js.FuncOf(wrapperSignaling.SignalingHeartbeat))
	js.Global().Set("signalingGetRoomByGroupID", js.FuncOf(wrapperSignaling.SignalingGetRoomByGroupID))
	js.Global().Set("signalingGetTokenByRoomID", js.FuncOf(wrapperSignaling.SignalingGetTokenByRoomID))
	js.Global().Set("signalingGetInvitationRecords", js.FuncOf(wrapperSignaling.SignalingGetInvitationRecords))
	js.Global().Set("signalingGetLocalCallRecords", js.FuncOf(wrapperSignaling.SignalingGetLocalCallRecords))
	js.Global().Set("signalingGetLocalCallRecordsWithUser", js.FuncOf(wrapperSignaling.SignalingGetLocalCallRecordsWithUser))
	js.Global().Set("signalingGetLocalMissedCallRecords", js.FuncOf(wrapperSignaling.SignalingGetLocalMissedCallRecords))
	js.Global().Set("signalingGetLocalAnsweredCallRecords", js.FuncOf(wrapperSignaling.SignalingGetLocalAnsweredCallRecords))
	js.Global().Set("signalingGetLocalAllCallRecords", js.FuncOf(wrapperSignaling.SignalingGetLocalAllCallRecords))
	js.Global().Set("signalingGetLocalCallRecordsByUserName", js.FuncOf(wrapperSignaling.SignalingGetLocalCallRecordsByUserName))
	js.Global().Set("signalingSearchLocalCallRecords", js.FuncOf(wrapperSignaling.SignalingSearchLocalCallRecords))
	js.Global().Set("signalingGetLocalCallRecordDetail", js.FuncOf(wrapperSignaling.SignalingGetLocalCallRecordDetail))
	js.Global().Set("signalingDeleteLocalCallRecords", js.FuncOf(wrapperSignaling.SignalingDeleteLocalCallRecords))
	js.Global().Set("signalingDeleteSignalRecords", js.FuncOf(wrapperSignaling.SignalingDeleteSignalRecords))
	js.Global().Set("signalingClearAllLocalCallRecords", js.FuncOf(wrapperSignaling.SignalingClearAllLocalCallRecords))
	js.Global().Set("signalingClearAllCallRecords", js.FuncOf(wrapperSignaling.SignalingClearAllCallRecords))
	js.Global().Set("signalingSendCustomSignal", js.FuncOf(wrapperSignaling.SignalingSendCustomSignal))
	js.Global().Set("signalingNotifyGroupCallEnded", js.FuncOf(wrapperSignaling.SignalingNotifyGroupCallEnded))

	wrapperRedPacket := wasm_wrapper.NewWrapperRedPacket(globalFuc)
	js.Global().Set("redPacketCreateOrder", js.FuncOf(wrapperRedPacket.RedPacketCreateOrder))
	js.Global().Set("redPacketCreatedCallback", js.FuncOf(wrapperRedPacket.RedPacketCreatedCallback))
	js.Global().Set("redPacketGetDetail", js.FuncOf(wrapperRedPacket.RedPacketGetDetail))
	js.Global().Set("redPacketIssueClaimSign", js.FuncOf(wrapperRedPacket.RedPacketIssueClaimSign))
	js.Global().Set("redPacketClaimResult", js.FuncOf(wrapperRedPacket.RedPacketClaimResult))
	js.Global().Set("redPacketRequestRefund", js.FuncOf(wrapperRedPacket.RedPacketRequestRefund))
	js.Global().Set("redPacketGetRefund", js.FuncOf(wrapperRedPacket.RedPacketGetRefund))
	js.Global().Set("redPacketIssueWalletBindChallenge", js.FuncOf(wrapperRedPacket.RedPacketIssueWalletBindChallenge))
	js.Global().Set("redPacketConfirmWalletBind", js.FuncOf(wrapperRedPacket.RedPacketConfirmWalletBind))
	js.Global().Set("redPacketGetWalletBinding", js.FuncOf(wrapperRedPacket.RedPacketGetWalletBinding))

}
